# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7"
  config.vm.synced_folder "..", "/vagrant"

  config.vm.provision "shell", path: "bootstrap.sh"
  config.vm.network "private_network", type: "dhcp"

  # Single machine hostname
  config.vm.hostname = "wildfly1.vagrant.box"

  # Multi-machine configuration
  # config.vm.define "server1" do |s1|
  #   s1.vm.hostname = "server1.vagrant.box"
  # end
  #
  # config.vm.define "server2" do |s2|
  #   s2.vm.hostname = "server2.vagrant.box"
  # end

end
